// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TinyFileIO.Data;

#nullable disable

namespace TinyFileIO.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260522131030_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.8");

            modelBuilder.Entity("TinyFileIO.Models.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<bool>("IsSuperAdmin")
                        .HasColumnType("INTEGER")
                        .HasColumnName("is_super_admin");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("TEXT")
                        .HasColumnName("password");

                    b.Property<string>("Salt")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT")
                        .HasColumnName("salt");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT")
                        .HasColumnName("username");

                    b.HasKey("Id");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("users");
                });

            modelBuilder.Entity("TinyFileIO.Models.Entities.UserAcl", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<string>("BucketName")
                        .HasMaxLength(63)
                        .HasColumnType("TEXT")
                        .HasColumnName("bucket_name");

                    b.Property<bool>("CanAdd")
                        .HasColumnType("INTEGER")
                        .HasColumnName("can_add");

                    b.Property<bool>("CanDelete")
                        .HasColumnType("INTEGER")
                        .HasColumnName("can_delete");

                    b.Property<bool>("CanRead")
                        .HasColumnType("INTEGER")
                        .HasColumnName("can_read");

                    b.Property<bool>("CanUpdate")
                        .HasColumnType("INTEGER")
                        .HasColumnName("can_update");

                    b.Property<Guid>("UserId")
                        .HasColumnType("TEXT")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "BucketName")
                        .IsUnique();

                    b.ToTable("user_acls");
                });

            modelBuilder.Entity("TinyFileIO.Models.Entities.UserAcl", b =>
                {
                    b.HasOne("TinyFileIO.Models.Entities.User", "User")
                        .WithMany("Acls")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("TinyFileIO.Models.Entities.User", b =>
                {
                    b.Navigation("Acls");
                });
#pragma warning restore 612, 618
        }
    }
}
