// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TinyFileIO.Data;

#nullable disable

namespace TinyFileIO.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.8");

            modelBuilder.Entity("TinyFileIO.Models.Entities.BackgroundJobRun", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<long>("BytesProcessed")
                        .HasColumnType("INTEGER")
                        .HasColumnName("bytes_processed");

                    b.Property<string>("CreatedByUserId")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT")
                        .HasColumnName("created_by_user_id");

                    b.Property<string>("CreatedByUsername")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT")
                        .HasColumnName("created_by_username");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_utc");

                    b.Property<string>("Error")
                        .HasColumnType("TEXT")
                        .HasColumnName("error");

                    b.Property<int>("FailedItems")
                        .HasColumnType("INTEGER")
                        .HasColumnName("failed_items");

                    b.Property<DateTime?>("FinishedUtc")
                        .HasColumnType("TEXT")
                        .HasColumnName("finished_utc");

                    b.Property<string>("JobType")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT")
                        .HasColumnName("job_type");

                    b.Property<string>("ParametersJson")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("parameters_json");

                    b.Property<int>("ProcessedItems")
                        .HasColumnType("INTEGER")
                        .HasColumnName("processed_items");

                    b.Property<int>("SkippedItems")
                        .HasColumnType("INTEGER")
                        .HasColumnName("skipped_items");

                    b.Property<DateTime?>("StartedUtc")
                        .HasColumnType("TEXT")
                        .HasColumnName("started_utc");

                    b.Property<string>("StatsJson")
                        .HasColumnType("TEXT")
                        .HasColumnName("stats_json");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT")
                        .HasColumnName("status");

                    b.Property<int>("SucceededItems")
                        .HasColumnType("INTEGER")
                        .HasColumnName("succeeded_items");

                    b.Property<string>("TargetBucket")
                        .HasMaxLength(63)
                        .HasColumnType("TEXT")
                        .HasColumnName("target_bucket");

                    b.Property<int>("TotalItems")
                        .HasColumnType("INTEGER")
                        .HasColumnName("total_items");

                    b.HasKey("Id");

                    b.HasIndex("CreatedUtc");

                    b.HasIndex("JobType", "Status");

                    b.ToTable("background_job_runs");
                });

            modelBuilder.Entity("TinyFileIO.Models.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<bool>("IsSuperAdmin")
                        .HasColumnType("INTEGER")
                        .HasColumnName("is_super_admin");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("TEXT")
                        .HasColumnName("password");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT")
                        .HasColumnName("username");

                    b.HasKey("Id");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("users");
                });

            modelBuilder.Entity("TinyFileIO.Models.Entities.UserAcl", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<string>("BucketName")
                        .HasMaxLength(63)
                        .HasColumnType("TEXT")
                        .HasColumnName("bucket_name");

                    b.Property<bool>("CanAdd")
                        .HasColumnType("INTEGER")
                        .HasColumnName("can_add");

                    b.Property<bool>("CanDelete")
                        .HasColumnType("INTEGER")
                        .HasColumnName("can_delete");

                    b.Property<bool>("CanRead")
                        .HasColumnType("INTEGER")
                        .HasColumnName("can_read");

                    b.Property<bool>("CanUpdate")
                        .HasColumnType("INTEGER")
                        .HasColumnName("can_update");

                    b.Property<Guid>("UserId")
                        .HasColumnType("TEXT")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "BucketName")
                        .IsUnique();

                    b.ToTable("user_acls");
                });

            modelBuilder.Entity("TinyFileIO.Models.Entities.UserAcl", b =>
                {
                    b.HasOne("TinyFileIO.Models.Entities.User", "User")
                        .WithMany("Acls")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("TinyFileIO.Models.Entities.User", b =>
                {
                    b.Navigation("Acls");
                });
#pragma warning restore 612, 618
        }
    }
}
